#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

timezone: "Asia/Shanghai"

initImage:
  pullPolicy: "IfNotPresent"
  busybox: "ccr-2owfeef4-pub.cnc.bj.baidubce.com/scheduler/busybox:1.30.1"

image:
  registry: ccr-2owfeef4-pub.cnc.bj.baidubce.com/scheduler
  tag: 3.4.1
  pullPolicy: "Always"
  pullSecret: "storm-ccr-pull-image-secret"
  master: dolphinscheduler-master
  worker: dolphinscheduler-worker
  api: dolphinscheduler-api
  alert: dolphinscheduler-alert-server
  tools: dolphinscheduler-tools

datasource:
  profile: postgresql

postgresql:
  enabled: false
  postgresqlUsername: "root"
  postgresqlPassword: "root"
  postgresqlDatabase: "dolphinscheduler"
  driverClassName: "org.postgresql.Driver"
  params: "characterEncoding=utf8"
  persistence:
    enabled: false
    size: "20Gi"
    storageClass: ""
  image:
    registry: ccr-2owfeef4-pub.cnc.bj.baidubce.com/scheduler
    repository: postgresql
    tag: 11.11.0
    pullSecrets:
      - storm-ccr-pull-image-secret

mysql:
  enabled: false
  driverClassName: "com.mysql.cj.jdbc.Driver"
  auth:
    username: "ds"
    password: "ds"
    database: "dolphinscheduler"
    params: "characterEncoding=utf8"
  primary:
    persistence:
      enabled: false
      size: "20Gi"
      storageClass: ""
  image:
    registry: ccr-2owfeef4-pub.cnc.bj.baidubce.com/scheduler
    repository: mysql
    tag: 8.0.31-debian-11-r0
    pullSecrets:
      - storm-ccr-pull-image-secret

minio:
  enabled: false
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
  persistence:
    enabled: false
    size: "20Gi"
    storageClass: ""
  defaultBuckets: "dolphinscheduler"
  image:
    registry: ccr-2owfeef4-pub.cnc.bj.baidubce.com/scheduler
    repository: minio
    tag: 2022.10.29-debian-11-r0
    pullPolicy: Always
    pullSecrets:
      - storm-ccr-pull-image-secret

externalDatabase:
  enabled: true
  type: "postgresql"
  host: "192.168.48.2"
  port: "5432"
  username: "dolphin_user"
  password: "u3P3s#uRcD5h@"
  database: "dolphinscheduler"
  params: "currentSchema=public"
  driverClassName: "org.postgresql.Driver"

zookeeper:
  enabled: true
  replicaCount: 3
  service:
    port: 2181
  fourlwCommandsWhitelist: "srvr,ruok,wchs,cons"
  resources:
    limits:
      memory: "2Gi"
      cpu: "1"
    requests:
      memory: "512Mi"
      cpu: "250m"
  persistence:
    enabled: true
    size: "20Gi"
    storageClass: "cfs-shared-sc"
  image:
    registry: ccr-2owfeef4-pub.cnc.bj.baidubce.com/scheduler
    repository: zookeeper
    tag: 3.8.4
    pullPolicy: "Always"
    pullSecrets:
      - storm-ccr-pull-image-secret

registryEtcd:
  enabled: false
  endpoints: ""
  namespace: "dolphinscheduler"
  user: ""
  passWord: ""
  authority: ""
  ssl:
    enabled: false
    certFile: "etcd-certs/ca.crt"
    keyCertChainFile: "etcd-certs/client.crt"
    keyFile: "etcd-certs/client.pem"

registryJdbc:
  enabled: false
  termRefreshInterval: 2s
  termExpireTimes: 3
  hikariConfig:
    enabled: false
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcurl: jdbc:mysql://
    username: ""
    password: ""

externalRegistry:
  registryPluginName: "zookeeper"
  registryServers: ""

security:
  authentication:
    type: PASSWORD
    ldap:
      url: ldap://ldap.forumsys.com:389/
      basedn: dc=example,dc=com
      username: cn=read-only-admin,dc=example,dc=com
      password: password
      user:
        adminuserfilter: (&(uid={0})(memberOf=cn=admin-group,ou=apps,dc=example,dc=com))
        adminusername: read-only-admin
        identityattribute: uid
        emailattribute: mail
        notexistaction: CREATE
      ssl:
        enable: false
        truststore: "/opt/ldapkeystore.jks"
        jksbase64content: ""
        truststorepassword: ""

conf:
  auto: false
  worker:
    resource.storage.type: LOCAL
  common:
    data.basedir.path: /tmp/dolphinscheduler
    resource.storage.type: LOCAL
    resource.storage.upload.base.path: /data/dolphinscheduler

    aws.credentials.provider.type: AWSStaticCredentialsProvider
    aws.s3.access.key.id: minioadmin
    aws.s3.access.key.secret: minioadmin
    aws.s3.region: us-east-1
    aws.s3.bucket.name: dolphinscheduler
    aws.s3.endpoint: http://dolphinscheduler-minio:9000

    resource.alibaba.cloud.access.key.id: <your-access-key-id>
    resource.alibaba.cloud.access.key.secret: <your-access-key-secret>
    resource.alibaba.cloud.region: cn-hangzhou
    resource.alibaba.cloud.oss.bucket.name: dolphinscheduler
    resource.alibaba.cloud.oss.endpoint: https://oss-cn-hangzhou.aliyuncs.com

    resource.azure.client.id: minioadmin
    resource.azure.client.secret: minioadmin
    resource.azure.subId: minioadmin
    resource.azure.tenant.id: minioadmin

    resource.hdfs.root.user: hdfs
    resource.hdfs.fs.defaultFS: hdfs://mycluster:8020
    hadoop.security.authentication.startup.state: false
    java.security.krb5.conf.path: /opt/krb5.conf
    login.user.keytab.username: hdfs-mycluster@ESZ.COM
    login.user.keytab.path: /opt/hdfs.headless.keytab
    kerberos.expire.time: 2
    resource.manager.httpaddress.port: 8088
    yarn.resourcemanager.ha.rm.ids: 192.168.xx.xx,192.168.xx.xx
    yarn.application.status.address: http://ds1:%s/ws/v1/cluster/apps/%s
    yarn.job.history.status.address: http://ds1:19888/ws/v1/history/mapreduce/jobs/%s
    datasource.encryption.enable: false
    datasource.encryption.salt: '!@#$%^&*'
    support.hive.oneSession: false
    sudo.enable: true
    development.state: false
    shell.kill.wait.timeout: 10
    conda.path: /opt/anaconda3/etc/profile.d/conda.sh
    task.resource.limit.state: false
    ml.mlflow.preset_repository: https://github.com/apache/dolphinscheduler-mlflow
    ml.mlflow.preset_repository_version: "main"
    appId.collect: log

common:
  configmap:
    DOLPHINSCHEDULER_OPTS: ""
    DATA_BASEDIR_PATH: "/tmp/dolphinscheduler"
    RESOURCE_UPLOAD_PATH: "/data/dolphinscheduler"
    RESOURCE_STORAGE_TYPE: "LOCAL"

    HADOOP_HOME: "/opt/soft/hadoop"
    HADOOP_CONF_DIR: "/opt/soft/hadoop/etc/hadoop"
    SPARK_HOME: "/opt/soft/spark"
    PYTHON_LAUNCHER: "/usr/bin/python/bin/python3"
    JAVA_HOME: "/opt/java/openjdk"
    HIVE_HOME: "/opt/soft/hive"
    FLINK_HOME: "/opt/soft/flink"
    DATAX_LAUNCHER: "/opt/soft/datax/bin/datax.py"
    MANAGEMENT_SECURITY_ENABLED: false
    MANAGEMENT_SECURITY_USERNAME: ""
    MANAGEMENT_SECURITY_PASSWORD: ""
    MANAGEMENT_SECURITY_EXCLUDE: "health,metrics"

  sharedStoragePersistence:
    enabled: true
    mountPath: "/data/dolphinscheduler"
    accessModes:
      - "ReadWriteMany"
    storageClassName: "cfs-shared-sc"
    storage: "50Gi"

  fsFileResourcePersistence:
    enabled: false

master:
  enabled: true
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: RollingUpdate
  replicas: "3"
  annotations: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources:
    limits:
      memory: "8Gi"
      cpu: "4"
    requests:
      memory: "2Gi"
      cpu: "500m"
  enableCustomizedConfig: false
  customizedConfig: { }
  livenessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  readinessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  persistentVolumeClaim:
    enabled: false

  env:
    JAVA_OPTS: "-Xms1g -Xmx1g -Xmn512m"
    MASTER_EXEC_THREADS: "100"
    MASTER_EXEC_TASK_NUM: "20"
    MASTER_DISPATCH_TASK_NUM: "3"
    MASTER_HOST_SELECTOR: "LowerWeight"
    MASTER_MAX_HEARTBEAT_INTERVAL: "10s"
    MASTER_HEARTBEAT_ERROR_THRESHOLD: "5"
    MASTER_TASK_COMMIT_RETRYTIMES: "5"
    MASTER_TASK_COMMIT_INTERVAL: "1s"
    MASTER_STATE_WHEEL_INTERVAL: "5s"
    MASTER_SERVER_LOAD_PROTECTION_ENABLED: false
    MASTER_FAILOVER_INTERVAL: "10m"
    MASTER_KILL_APPLICATION_WHEN_HANDLE_FAILOVER: "true"
  service:
    annotations: {}
    serviceMonitor:
      enabled: false

worker:
  enabled: true
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: RollingUpdate
  replicas: "1"
  annotations: {}
  affinity: {}
  nodeSelector: {}
  tolerations: [ ]
  resources:
    limits:
      memory: "8Gi"
      cpu: "4"
    requests:
      memory: "2Gi"
      cpu: "500m"
  enableCustomizedConfig: false
  customizedConfig: { }
  livenessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  readinessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  persistentVolumeClaim:
    enabled: false

  env:
    WORKER_SERVER_LOAD_PROTECTION_ENABLED: false
    WORKER_EXEC_THREADS: "100"
    WORKER_MAX_HEARTBEAT_INTERVAL: "10s"
    WORKER_HOST_WEIGHT: "100"
    WORKER_TENANT_CONFIG_AUTO_CREATE_TENANT_ENABLED: true
  keda:
    enabled: false
  service:
    annotations: {}
    serviceMonitor:
      enabled: false

alert:
  enabled: true
  replicas: 1
  strategy:
    type: "RollingUpdate"
  annotations: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources:
    limits:
      memory: "2Gi"
      cpu: "1"
    requests:
      memory: "1Gi"
      cpu: "500m"
  enableCustomizedConfig: false
  customizedConfig: { }
  livenessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  readinessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  persistentVolumeClaim:
    enabled: false
  env:
    JAVA_OPTS: "-Xms512m -Xmx512m -Xmn256m"
  service:
    annotations: {}
    serviceMonitor:
      enabled: false

api:
  enabled: true
  replicas: "1"
  strategy:
    type: "RollingUpdate"
  annotations: {}
  affinity: { }
  nodeSelector: { }
  tolerations: [ ]
  resources:
    limits:
      memory: "2Gi"
      cpu: "1"
    requests:
      memory: "1Gi"
      cpu: "500m"
  enableCustomizedConfig: false
  customizedConfig: { }
  livenessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  readinessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  persistentVolumeClaim:
    enabled: false

  service:
    type: "ClusterIP"
    annotations: {}
    serviceMonitor:
      enabled: false
  env:
    JAVA_OPTS: "-Xms512m -Xmx512m -Xmn256m"
  taskTypeFilter:
    enabled: false

ingress:
  enabled: false
  tls:
    enabled: false