apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphinscheduler-cfs-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: dolphinscheduler-cfs-pv