ssl.cert.file.path=/opt/bmr/sts/ca/ca-cert.pem
ssl.key.file.path=/opt/bmr/sts/ca/ca-key.pem
ssl.trust.file.path=/opt/bmr/sts/ca/ca-cert.pem
java.security.auth.login.config=/opt/bmr/sts/client_conf/sts_jaas_client.conf
      

sasl.kerberos.principal.to.local.rules=RULE:[1:$1@$0](.*@)s/@.*//,DEFAULT

sts.endpoints=192.168.16.204,192.168.16.209,192.168.16.208